---
driver:
  name: ec2
  aws_ssh_key_id: vc1ec2 
  region: us-east-1
  availability_zone: b
  subnet_id: subnet-c06aed99
  instance_type: t2.micro
  image_id: ami-26ebbc5c
  security_group_ids: ["sg-328c8045"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /Users/vsagarch/Documents/Projects/AWS/vc1ec2.pem

platforms:
  - name: RHEL

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
